# Generated by Django 3.2.6 on 2021-08-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0004_auto_20210823_0941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
